### ISSUE TITLE
Getting started installation not working

### ISSUE THREAD

**Issue by mwaaas** [buger/cloud-ssh#11]

**Comment by buger** [comment]
Fixed!

**Comment by mwaaas** [comment]
@buger  Its still not working. I have attached the error logs am getting
<img width="745" alt="screen shot 2017-02-14 at 1 40 43 pm" src="https://cloud.githubusercontent.com/assets/6207932/22925730/e58b1e58-f2ba-11e6-9354-6d87712d6cf3.png">

**Comment by buger** [comment]
Right, it should have been "https" instead of "http" and github.io instead of github.com. Now fixed and "checked" 👍
